#pragma once

#define DYNAMIC_KEYMAP_LAYER_COUNT 12

#define SPLIT_POINTING_ENABLE
#define SPLIT_LED_STATE_ENABLE
#define SPLIT_TRANSPORT_MIRROR
#define SPLIT_LAYER_STATE_ENABLE

#define MASTER_RIGHT
